/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProjectsListResponse {
    projects: ProjectsListResponse.Projects.Item[];
    hasNextPage: boolean;
}

export namespace ProjectsListResponse {
    export type Projects = Projects.Item[];

    export namespace Projects {
        export interface Item {
            name: string;
            slug: string;
            id: string;
        }
    }
}
