/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const ClientSideAccessTokensListClientSideAccessTokensResponseTokensItemPolicyDataItemAccessItem: core.serialization.Schema<
    serializers.ClientSideAccessTokensListClientSideAccessTokensResponseTokensItemPolicyDataItemAccessItem.Raw,
    Letta.ClientSideAccessTokensListClientSideAccessTokensResponseTokensItemPolicyDataItemAccessItem
> = core.serialization.enum_(["read_messages", "write_messages", "read_agent", "write_agent"]);

export declare namespace ClientSideAccessTokensListClientSideAccessTokensResponseTokensItemPolicyDataItemAccessItem {
    export type Raw = "read_messages" | "write_messages" | "read_agent" | "write_agent";
}
