/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface CreateVoiceChatCompletionsRequest {
    "user-id"?: string;
    body: Record<string, unknown>;
}
