/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { StdioServerConfig } from "../../../types/StdioServerConfig";
import { SseServerConfig } from "../../../types/SseServerConfig";
import { StreamableHttpServerConfig } from "../../../types/StreamableHttpServerConfig";

export const ConnectMcpServerRequest: core.serialization.Schema<
    serializers.ConnectMcpServerRequest.Raw,
    Letta.ConnectMcpServerRequest
> = core.serialization.undiscriminatedUnion([StdioServerConfig, SseServerConfig, StreamableHttpServerConfig]);

export declare namespace ConnectMcpServerRequest {
    export type Raw = StdioServerConfig.Raw | SseServerConfig.Raw | StreamableHttpServerConfig.Raw;
}
