/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         requiresApproval: true
 *     }
 */
export interface ModifyApprovalRequest {
    requiresApproval: boolean;
}
