/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateAgentState {
    /** The description of the agent. */
    description?: string;
    /** The metadata of the agent. */
    metadata_?: Record<string, unknown>;
    /** The user id of the agent. */
    user_id?: string;
    /** The id of the agent. */
    id: string;
    /** The name of the agent. */
    name?: string;
    /** The tools used by the agent. */
    tools?: string[];
    /** The tags associated with the agent. */
    tags?: string[];
    /** The system prompt used by the agent. */
    system?: string;
    /** The LLM configuration used by the agent. */
    llm_config?: Letta.LlmConfig;
    /** The embedding configuration used by the agent. */
    embedding_config?: Letta.EmbeddingConfig;
    /** The ids of the messages in the agent's in-context memory. */
    message_ids?: string[];
    /** The in-context memory of the agent. */
    memory?: Letta.Memory;
}
