/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { Step } from "../../../types/Step";

export const Response: core.serialization.Schema<serializers.runs.listRunSteps.Response.Raw, Letta.Step[]> =
    core.serialization.list(Step);

export declare namespace Response {
    export type Raw = Step.Raw[];
}
