/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateResponseGroupSleeptimeAgentFrequencyItem } from "./AgentsCreateResponseGroupSleeptimeAgentFrequencyItem";

export const AgentsCreateResponseGroupSleeptimeAgentFrequency: core.serialization.Schema<
    serializers.templates.AgentsCreateResponseGroupSleeptimeAgentFrequency.Raw,
    Letta.templates.AgentsCreateResponseGroupSleeptimeAgentFrequency
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsCreateResponseGroupSleeptimeAgentFrequencyItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsCreateResponseGroupSleeptimeAgentFrequency {
    export type Raw =
        | number
        | (string | null | undefined)
        | (AgentsCreateResponseGroupSleeptimeAgentFrequencyItem.Raw | null | undefined)[]
        | unknown;
}
