/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateRequestInitialMessageSequenceItemRole } from "./AgentsCreateRequestInitialMessageSequenceItemRole";

export const AgentsCreateRequestInitialMessageSequenceItem: core.serialization.ObjectSchema<
    serializers.templates.AgentsCreateRequestInitialMessageSequenceItem.Raw,
    Letta.templates.AgentsCreateRequestInitialMessageSequenceItem
> = core.serialization.object({
    role: AgentsCreateRequestInitialMessageSequenceItemRole,
    content: core.serialization.string(),
    name: core.serialization.string().optional(),
    otid: core.serialization.string().optional(),
    senderId: core.serialization.property("sender_id", core.serialization.string().optional()),
    batchItemId: core.serialization.property("batch_item_id", core.serialization.string().optional()),
    groupId: core.serialization.property("group_id", core.serialization.string().optional()),
});

export declare namespace AgentsCreateRequestInitialMessageSequenceItem {
    export interface Raw {
        role: AgentsCreateRequestInitialMessageSequenceItemRole.Raw;
        content: string;
        name?: string | null;
        otid?: string | null;
        sender_id?: string | null;
        batch_item_id?: string | null;
        group_id?: string | null;
    }
}
