/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateResponseGroupTurnsCounterItem } from "./AgentsCreateResponseGroupTurnsCounterItem";

export const AgentsCreateResponseGroupTurnsCounter: core.serialization.Schema<
    serializers.templates.AgentsCreateResponseGroupTurnsCounter.Raw,
    Letta.templates.AgentsCreateResponseGroupTurnsCounter
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsCreateResponseGroupTurnsCounterItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsCreateResponseGroupTurnsCounter {
    export type Raw =
        | number
        | (string | null | undefined)
        | (AgentsCreateResponseGroupTurnsCounterItem.Raw | null | undefined)[]
        | unknown;
}
