/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateResponseGroupHiddenItem } from "./AgentsCreateResponseGroupHiddenItem";

export const AgentsCreateResponseGroupHidden: core.serialization.Schema<
    serializers.templates.AgentsCreateResponseGroupHidden.Raw,
    Letta.templates.AgentsCreateResponseGroupHidden
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsCreateResponseGroupHiddenItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsCreateResponseGroupHidden {
    export type Raw =
        | boolean
        | (string | null | undefined)
        | (AgentsCreateResponseGroupHiddenItem.Raw | null | undefined)[]
        | unknown;
}
