/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateResponseGroupTemplateIdItem } from "./AgentsCreateResponseGroupTemplateIdItem";

export const AgentsCreateResponseGroupTemplateId: core.serialization.Schema<
    serializers.templates.AgentsCreateResponseGroupTemplateId.Raw,
    Letta.templates.AgentsCreateResponseGroupTemplateId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsCreateResponseGroupTemplateIdItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsCreateResponseGroupTemplateId {
    export type Raw =
        | string
        | (string | null | undefined)
        | (AgentsCreateResponseGroupTemplateIdItem.Raw | null | undefined)[]
        | unknown;
}
