/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { AgentsCreateResponseGroupMaxMessageBufferLengthItem } from "./AgentsCreateResponseGroupMaxMessageBufferLengthItem";

export const AgentsCreateResponseGroupMaxMessageBufferLength: core.serialization.Schema<
    serializers.templates.AgentsCreateResponseGroupMaxMessageBufferLength.Raw,
    Letta.templates.AgentsCreateResponseGroupMaxMessageBufferLength
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsCreateResponseGroupMaxMessageBufferLengthItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsCreateResponseGroupMaxMessageBufferLength {
    export type Raw =
        | number
        | (string | null | undefined)
        | (AgentsCreateResponseGroupMaxMessageBufferLengthItem.Raw | null | undefined)[]
        | unknown;
}
