/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageIdItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageIdItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageId: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageId.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageIdItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageId {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupItemAgentIdsLastProcessedMessageIdItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
