/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolNameType } from "./TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolNameType";

export const TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolName: core.serialization.ObjectSchema<
    serializers.TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolName.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolName
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolNameType.optional(),
});

export declare namespace TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolName {
    export interface Raw {
        tool_name: string;
        type?: TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemToolNameType.Raw | null;
    }
}
