/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIdsManagerType: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIdsManagerType.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIdsManagerType
> = core.serialization.enum_(["round_robin", "supervisor", "dynamic", "swarm"]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIdsManagerType {
    export type Raw = "round_robin" | "supervisor" | "dynamic" | "swarm";
}
