/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesGetTemplateSnapshotResponseRelationshipsItem: core.serialization.ObjectSchema<
    serializers.TemplatesGetTemplateSnapshotResponseRelationshipsItem.Raw,
    Letta.TemplatesGetTemplateSnapshotResponseRelationshipsItem
> = core.serialization.object({
    agentEntityId: core.serialization.string(),
    blockEntityId: core.serialization.string(),
});

export declare namespace TemplatesGetTemplateSnapshotResponseRelationshipsItem {
    export interface Raw {
        agentEntityId: string;
        blockEntityId: string;
    }
}
