/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroType } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroType";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroPromptTemplate } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroPromptTemplate";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZero: core.serialization.ObjectSchema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZero.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZero
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroType.optional(),
    promptTemplate: core.serialization.property(
        "prompt_template",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroPromptTemplate.optional(),
    ),
    children: core.serialization.list(core.serialization.string()),
});

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZero {
    export interface Raw {
        tool_name: string;
        type?: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroType.Raw | null;
        prompt_template?: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemZeroPromptTemplate.Raw | null;
        children: string[];
    }
}
