/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsResponseAgentsItemEmbeddingConfigEmbeddingEndpointType: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemEmbeddingConfigEmbeddingEndpointType.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemEmbeddingConfigEmbeddingEndpointType
> = core.serialization.enum_([
    "openai",
    "anthropic",
    "bedrock",
    "cohere",
    "google_ai",
    "google_vertex",
    "azure",
    "groq",
    "ollama",
    "webui",
    "webui-legacy",
    "lmstudio",
    "lmstudio-legacy",
    "llamacpp",
    "koboldcpp",
    "vllm",
    "hugging-face",
    "mistral",
    "together",
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemEmbeddingConfigEmbeddingEndpointType {
    export type Raw =
        | "openai"
        | "anthropic"
        | "bedrock"
        | "cohere"
        | "google_ai"
        | "google_vertex"
        | "azure"
        | "groq"
        | "ollama"
        | "webui"
        | "webui-legacy"
        | "lmstudio"
        | "lmstudio-legacy"
        | "llamacpp"
        | "koboldcpp"
        | "vllm"
        | "hugging-face"
        | "mistral"
        | "together";
}
