/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIds } from "./TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIds";

export const TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItem: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItem.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItem
> = core.serialization.undiscriminatedUnion([
    TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIds,
    core.serialization.string().optional(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItem {
    export type Raw =
        | TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupItemAgentIds.Raw
        | (string | null | undefined);
}
