/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemTwo: core.serialization.ObjectSchema<
    serializers.TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemTwo.Raw,
    Letta.TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemTwo
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: core.serialization.stringLiteral("exit_loop").optional(),
    promptTemplate: core.serialization.property("prompt_template", core.serialization.string().optional()),
});

export declare namespace TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemTwo {
    export interface Raw {
        tool_name: string;
        type?: "exit_loop" | null;
        prompt_template?: string | null;
    }
}
