/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenType } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenType";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenPromptTemplate } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenPromptTemplate";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSeven: core.serialization.ObjectSchema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSeven.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSeven
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenType.optional(),
    promptTemplate: core.serialization.property(
        "prompt_template",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenPromptTemplate.optional(),
    ),
    children: core.serialization.list(core.serialization.string()),
});

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSeven {
    export interface Raw {
        tool_name: string;
        type?: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenType.Raw | null;
        prompt_template?: TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemSevenPromptTemplate.Raw | null;
        children: string[];
    }
}
