/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemOneType: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemOneType.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemOneType
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("run_first"),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemOneType {
    export type Raw = "run_first" | unknown;
}
