/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpoint } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpoint";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelWrapper } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelWrapper";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigHandle } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigHandle";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigTemperature } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigTemperature";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfig: core.serialization.ObjectSchema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfig.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfig
> = core.serialization.object({
    model: core.serialization.string(),
    modelEndpointType: core.serialization.property(
        "model_endpoint_type",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType,
    ),
    modelEndpoint: core.serialization.property(
        "model_endpoint",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpoint.optional(),
    ),
    modelWrapper: core.serialization.property(
        "model_wrapper",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelWrapper.optional(),
    ),
    contextWindow: core.serialization.property("context_window", core.serialization.number()),
    putInnerThoughtsInKwargs: core.serialization.property(
        "put_inner_thoughts_in_kwargs",
        TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs.optional(),
    ),
    handle: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigHandle.optional(),
    temperature: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigTemperature.optional(),
});

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfig {
    export interface Raw {
        model: string;
        model_endpoint_type: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType.Raw;
        model_endpoint?: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpoint.Raw | null;
        model_wrapper?: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelWrapper.Raw | null;
        context_window: number;
        put_inner_thoughts_in_kwargs?: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs.Raw | null;
        handle?: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigHandle.Raw | null;
        temperature?: TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigTemperature.Raw | null;
    }
}
