/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchemaItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchemaItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchema: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchema.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.unknown(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchemaItem.optional()),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchema {
    export type Raw =
        | unknown
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemArgsJsonSchemaItem.Raw | null | undefined)[];
}
