/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
