/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgsItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgsItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgs: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgs.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgs
> = core.serialization.undiscriminatedUnion([
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgsItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgs {
    export type Raw =
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemArgsArgsItem.Raw | null | undefined)[]
        | unknown;
}
