/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedByIdItem } from "./TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedByIdItem";

export const TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedById: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedById.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedById
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedByIdItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedById {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsResponseAgentsItemMemoryBlocksItemCreatedByIdItem.Raw | null | undefined)[]
        | unknown;
}
