/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemResponseFormatItemJsonSchemaType: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemResponseFormatItemJsonSchemaType.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemResponseFormatItemJsonSchemaType
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.unknown()]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemResponseFormatItemJsonSchemaType {
    export type Raw = string | unknown;
}
