/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplateItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplateItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplate: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplate.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplate
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplateItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplate {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplateItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
