/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesSetCurrentTemplateFromSnapshotResponse: core.serialization.ObjectSchema<
    serializers.TemplatesSetCurrentTemplateFromSnapshotResponse.Raw,
    Letta.TemplatesSetCurrentTemplateFromSnapshotResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
});

export declare namespace TemplatesSetCurrentTemplateFromSnapshotResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
    }
}
