/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemLastUpdatedByIdItem } from "./TemplatesCreateAgentsResponseAgentsItemLastUpdatedByIdItem";

export const TemplatesCreateAgentsResponseAgentsItemLastUpdatedById: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemLastUpdatedById.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemLastUpdatedById
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsResponseAgentsItemLastUpdatedByIdItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemLastUpdatedById {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsResponseAgentsItemLastUpdatedByIdItem.Raw | null | undefined)[]
        | unknown;
}
