/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsResponseAgentsItemMemoryPromptTemplate: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemMemoryPromptTemplate.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemMemoryPromptTemplate
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.unknown()]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemMemoryPromptTemplate {
    export type Raw = string | unknown;
}
