/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectIdItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectIdItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectId: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectId.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectIdItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectId {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemMultiAgentGroupAgentIdsProjectIdItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
