/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplateItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplateItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplate: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplate.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplate
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplateItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplate {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildArgNodesPromptTemplateItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
