/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemToolRulesItemOneType } from "./TemplatesCreateAgentsResponseAgentsItemToolRulesItemOneType";

export const TemplatesCreateAgentsResponseAgentsItemToolRulesItemOne: core.serialization.ObjectSchema<
    serializers.TemplatesCreateAgentsResponseAgentsItemToolRulesItemOne.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemToolRulesItemOne
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: TemplatesCreateAgentsResponseAgentsItemToolRulesItemOneType.optional(),
});

export declare namespace TemplatesCreateAgentsResponseAgentsItemToolRulesItemOne {
    export interface Raw {
        tool_name: string;
        type?: TemplatesCreateAgentsResponseAgentsItemToolRulesItemOneType.Raw | null;
    }
}
