/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplateItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplateItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplate: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplate.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplate
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(
        TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplateItem.optional(),
    ),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplate {
    export type Raw =
        | string
        | (string | null | undefined)
        | (
              | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemMaxCountLimitPromptTemplateItem.Raw
              | null
              | undefined
          )[]
        | unknown;
}
