/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesGetTemplateSnapshotResponseAgentsItemAgentType: core.serialization.Schema<
    serializers.TemplatesGetTemplateSnapshotResponseAgentsItemAgentType.Raw,
    Letta.TemplatesGetTemplateSnapshotResponseAgentsItemAgentType
> = core.serialization.enum_([
    "letta_v1_agent",
    "memgpt_agent",
    "memgpt_v2_agent",
    "react_agent",
    "workflow_agent",
    "split_thread_agent",
    "sleeptime_agent",
    "voice_convo_agent",
    "voice_sleeptime_agent",
]);

export declare namespace TemplatesGetTemplateSnapshotResponseAgentsItemAgentType {
    export type Raw =
        | "letta_v1_agent"
        | "memgpt_agent"
        | "memgpt_v2_agent"
        | "react_agent"
        | "workflow_agent"
        | "split_thread_agent"
        | "sleeptime_agent"
        | "voice_convo_agent"
        | "voice_sleeptime_agent";
}
