/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAtItem } from "./TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAtItem";

export const TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAt: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAt.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAt
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAtItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAt {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsResponseAgentsItemSourcesItemUpdatedAtItem.Raw | null | undefined)[]
        | unknown;
}
