/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAtItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAtItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAt: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAt.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAt
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAtItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAt {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemSourcesItemCreatedAtItem.Raw | null | undefined)[]
        | unknown;
}
