/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAtItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAtItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAt: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAt.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAt
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAtItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAt {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemCreatedAtItem.Raw | null | undefined)[]
        | unknown;
}
