/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemEmbeddingConfigAzureDeploymentItem: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemEmbeddingConfigAzureDeploymentItem.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemEmbeddingConfigAzureDeploymentItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.string().optional()]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemEmbeddingConfigAzureDeploymentItem {
    export type Raw = string | (string | null | undefined);
}
