/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemMaxCountLimit: core.serialization.ObjectSchema<
    serializers.TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemMaxCountLimit.Raw,
    Letta.TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemMaxCountLimit
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: core.serialization.stringLiteral("max_count_per_step").optional(),
    promptTemplate: core.serialization.property("prompt_template", core.serialization.string().optional()),
    maxCountLimit: core.serialization.property("max_count_limit", core.serialization.number()),
});

export declare namespace TemplatesGetTemplateSnapshotResponseAgentsItemToolRulesItemMaxCountLimit {
    export interface Raw {
        tool_name: string;
        type?: "max_count_per_step" | null;
        prompt_template?: string | null;
        max_count_limit: number;
    }
}
