/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildren } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildren";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOne } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOne";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemTwo } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemTwo";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildOutputMapping } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildOutputMapping";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemToolName } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemToolName";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItem: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItem.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItem
> = core.serialization.undiscriminatedUnion([
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildren,
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOne,
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemTwo,
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildOutputMapping,
    TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemToolName,
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItem {
    export type Raw =
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildren.Raw
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOne.Raw
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemTwo.Raw
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemChildOutputMapping.Raw
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemToolName.Raw;
}
