/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItemItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItemItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItem: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItem.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItemItem),
    core.serialization.string().optional(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItem {
    export type Raw =
        | TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemPipRequirementsItemItem.Raw[]
        | (string | null | undefined);
}
