/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemDefaultRequiresApprovalItem: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemDefaultRequiresApprovalItem.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemDefaultRequiresApprovalItem
> = core.serialization.undiscriminatedUnion([core.serialization.boolean(), core.serialization.string().optional()]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemDefaultRequiresApprovalItem {
    export type Raw = boolean | (string | null | undefined);
}
