/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceTypeItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceTypeItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceType: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceType.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceType
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceTypeItem.optional()),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceType {
    export type Raw =
        | string
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemToolsItemSourceTypeItem.Raw | null | undefined)[];
}
