/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsFromTemplateResponseAgentsItemHiddenItem } from "./TemplatesCreateAgentsFromTemplateResponseAgentsItemHiddenItem";

export const TemplatesCreateAgentsFromTemplateResponseAgentsItemHidden: core.serialization.Schema<
    serializers.TemplatesCreateAgentsFromTemplateResponseAgentsItemHidden.Raw,
    Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemHidden
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsFromTemplateResponseAgentsItemHiddenItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsFromTemplateResponseAgentsItemHidden {
    export type Raw =
        | boolean
        | (string | null | undefined)
        | (TemplatesCreateAgentsFromTemplateResponseAgentsItemHiddenItem.Raw | null | undefined)[]
        | unknown;
}
