/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { TemplatesCreateAgentsResponseAgentsItemMetadataItem } from "./TemplatesCreateAgentsResponseAgentsItemMetadataItem";

export const TemplatesCreateAgentsResponseAgentsItemMetadata: core.serialization.Schema<
    serializers.TemplatesCreateAgentsResponseAgentsItemMetadata.Raw,
    Letta.TemplatesCreateAgentsResponseAgentsItemMetadata
> = core.serialization.undiscriminatedUnion([
    core.serialization.string().optional(),
    core.serialization.list(TemplatesCreateAgentsResponseAgentsItemMetadataItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace TemplatesCreateAgentsResponseAgentsItemMetadata {
    export type Raw =
        | (string | null | undefined)
        | (TemplatesCreateAgentsResponseAgentsItemMetadataItem.Raw | null | undefined)[]
        | unknown;
}
