/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemToolRulesItemItemToolNameType } from "./AgentsSearchResponseAgentsItemToolRulesItemItemToolNameType";

export const AgentsSearchResponseAgentsItemToolRulesItemItemToolName: core.serialization.ObjectSchema<
    serializers.AgentsSearchResponseAgentsItemToolRulesItemItemToolName.Raw,
    Letta.AgentsSearchResponseAgentsItemToolRulesItemItemToolName
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: AgentsSearchResponseAgentsItemToolRulesItemItemToolNameType.optional(),
});

export declare namespace AgentsSearchResponseAgentsItemToolRulesItemItemToolName {
    export interface Raw {
        tool_name: string;
        type?: AgentsSearchResponseAgentsItemToolRulesItemItemToolNameType.Raw | null;
    }
}
