/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchRequestSearchItemOneOperator } from "./AgentsSearchRequestSearchItemOneOperator";

export const AgentsSearchRequestSearchItemOne: core.serialization.ObjectSchema<
    serializers.AgentsSearchRequestSearchItemOne.Raw,
    Letta.AgentsSearchRequestSearchItemOne
> = core.serialization.object({
    field: core.serialization.stringLiteral("name"),
    operator: AgentsSearchRequestSearchItemOneOperator,
    value: core.serialization.string(),
});

export declare namespace AgentsSearchRequestSearchItemOne {
    export interface Raw {
        field: "name";
        operator: AgentsSearchRequestSearchItemOneOperator.Raw;
        value: string;
    }
}
