/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargsItem } from "./AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargsItem";

export const AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs: core.serialization.Schema<
    serializers.AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs.Raw,
    Letta.AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargsItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargs {
    export type Raw =
        | boolean
        | (string | null | undefined)
        | (AgentsSearchResponseAgentsItemLlmConfigPutInnerThoughtsInKwargsItem.Raw | null | undefined)[]
        | unknown;
}
