/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemToolRulesItemTwoType } from "./AgentsSearchResponseAgentsItemToolRulesItemTwoType";

export const AgentsSearchResponseAgentsItemToolRulesItemTwo: core.serialization.ObjectSchema<
    serializers.AgentsSearchResponseAgentsItemToolRulesItemTwo.Raw,
    Letta.AgentsSearchResponseAgentsItemToolRulesItemTwo
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: AgentsSearchResponseAgentsItemToolRulesItemTwoType.optional(),
});

export declare namespace AgentsSearchResponseAgentsItemToolRulesItemTwo {
    export interface Raw {
        tool_name: string;
        type?: AgentsSearchResponseAgentsItemToolRulesItemTwoType.Raw | null;
    }
}
