/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemToolRulesItemItemOneType } from "./AgentsSearchResponseAgentsItemToolRulesItemItemOneType";

export const AgentsSearchResponseAgentsItemToolRulesItemItemOne: core.serialization.ObjectSchema<
    serializers.AgentsSearchResponseAgentsItemToolRulesItemItemOne.Raw,
    Letta.AgentsSearchResponseAgentsItemToolRulesItemItemOne
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: AgentsSearchResponseAgentsItemToolRulesItemItemOneType.optional(),
});

export declare namespace AgentsSearchResponseAgentsItemToolRulesItemItemOne {
    export interface Raw {
        tool_name: string;
        type?: AgentsSearchResponseAgentsItemToolRulesItemItemOneType.Raw | null;
    }
}
