/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersionItem } from "./AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersionItem";

export const AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersion: core.serialization.Schema<
    serializers.AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersion.Raw,
    Letta.AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersion
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.string().optional(),
    core.serialization.list(AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersionItem.optional()),
    core.serialization.unknown(),
]);

export declare namespace AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersion {
    export type Raw =
        | string
        | (string | null | undefined)
        | (AgentsSearchResponseAgentsItemEmbeddingConfigAzureVersionItem.Raw | null | undefined)[]
        | unknown;
}
