/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchDeployedAgentsRequestSearchItemOrderByValue } from "./AgentsSearchDeployedAgentsRequestSearchItemOrderByValue";
import { AgentsSearchDeployedAgentsRequestSearchItemOrderByDirection } from "./AgentsSearchDeployedAgentsRequestSearchItemOrderByDirection";

export const AgentsSearchDeployedAgentsRequestSearchItemOrderBy: core.serialization.ObjectSchema<
    serializers.AgentsSearchDeployedAgentsRequestSearchItemOrderBy.Raw,
    Letta.AgentsSearchDeployedAgentsRequestSearchItemOrderBy
> = core.serialization.object({
    value: AgentsSearchDeployedAgentsRequestSearchItemOrderByValue,
    direction: AgentsSearchDeployedAgentsRequestSearchItemOrderByDirection,
});

export declare namespace AgentsSearchDeployedAgentsRequestSearchItemOrderBy {
    interface Raw {
        value: AgentsSearchDeployedAgentsRequestSearchItemOrderByValue.Raw;
        direction: AgentsSearchDeployedAgentsRequestSearchItemOrderByDirection.Raw;
    }
}
