/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Letta from "../../../../api/index";
import * as core from "../../../../core";
import { AgentsSearchResponseAgentsItemToolRulesItemToolNameType } from "./AgentsSearchResponseAgentsItemToolRulesItemToolNameType";

export const AgentsSearchResponseAgentsItemToolRulesItemToolName: core.serialization.ObjectSchema<
    serializers.AgentsSearchResponseAgentsItemToolRulesItemToolName.Raw,
    Letta.AgentsSearchResponseAgentsItemToolRulesItemToolName
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: AgentsSearchResponseAgentsItemToolRulesItemToolNameType.optional(),
});

export declare namespace AgentsSearchResponseAgentsItemToolRulesItemToolName {
    export interface Raw {
        tool_name: string;
        type?: AgentsSearchResponseAgentsItemToolRulesItemToolNameType.Raw | null;
    }
}
