/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ModelsListRequest {
    provider_category?: Letta.ProviderCategory | Letta.ProviderCategory[];
    provider_name?: string;
    provider_type?: Letta.ProviderType;
}
