/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const MessagesListRequestOrder: core.serialization.Schema<
    serializers.steps.MessagesListRequestOrder.Raw,
    Letta.steps.MessagesListRequestOrder
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace MessagesListRequestOrder {
    export type Raw = "asc" | "desc";
}
