/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enum to represent the type of agent.
 */
export type AgentType = "memgpt_agent" | "split_thread_agent" | "offline_memory_agent";
export const AgentType = {
    MemgptAgent: "memgpt_agent",
    SplitThreadAgent: "split_thread_agent",
    OfflineMemoryAgent: "offline_memory_agent",
} as const;
