/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssistantMessageOutput {
    id: string;
    date: string;
    message_type: "assistant_message";
    assistant_message: string;
}
