/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

export interface ChatCompletionToolParam {
    function: Letta.FunctionDefinitionInput;
    type: "function";
}
