/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompletionCreateParamsStreamingReasoningEffort = "minimal" | "low" | "medium" | "high";
export const CompletionCreateParamsStreamingReasoningEffort = {
    Minimal: "minimal",
    Low: "low",
    Medium: "medium",
    High: "high",
} as const;
