/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompletionCreateParamsStreamingServiceTier = "auto" | "default" | "flex" | "scale" | "priority";
export const CompletionCreateParamsStreamingServiceTier = {
    Auto: "auto",
    Default: "default",
    Flex: "flex",
    Scale: "scale",
    Priority: "priority",
} as const;
