/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CompletionCreateParamsStreamingServiceTier = "auto" | "default" | "flex";
export const CompletionCreateParamsStreamingServiceTier = {
    Auto: "auto",
    Default: "default",
    Flex: "flex",
} as const;
