/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteAssistantFileResponse {
    /** The unique identifier of the file. */
    id: string;
    object?: string;
    /** Whether the file was deleted. */
    deleted: boolean;
}
