/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

/**
 * Representation of a folder, which is a collection of files and passages.
 *
 * Parameters:
 *     id (str): The ID of the folder
 *     name (str): The name of the folder.
 *     embedding_config (EmbeddingConfig): The embedding configuration used by the folder.
 *     user_id (str): The ID of the user that created the folder.
 *     metadata (dict): Metadata associated with the folder.
 *     description (str): The description of the folder.
 */
export interface Folder {
    /** The name of the folder. */
    name: string;
    /** The description of the folder. */
    description?: string;
    /** Instructions for how to use the folder. */
    instructions?: string;
    /** Metadata associated with the folder. */
    metadata?: Record<string, unknown>;
    /** The human-friendly ID of the Source */
    id?: string;
    /** The embedding configuration used by the folder. */
    embedding_config: Letta.EmbeddingConfig;
    /** The id of the user that made this Tool. */
    created_by_id?: string;
    /** The id of the user that made this Tool. */
    last_updated_by_id?: string;
    /** The timestamp when the folder was created. */
    created_at?: string;
    /** The timestamp when the folder was last updated. */
    updated_at?: string;
}
