/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

export interface Identity {
    /** The human-friendly ID of the Identity */
    id?: string;
    /** External, user-generated identifier key of the identity. */
    identifier_key: string;
    /** The name of the identity. */
    name: string;
    /** The type of the identity. */
    identity_type: Letta.IdentityType;
    /** The project id of the identity, if applicable. */
    project_id?: string;
    /** The IDs of the agents associated with the identity. */
    agent_ids: string[];
    /** The IDs of the blocks associated with the identity. */
    block_ids: string[];
    /** List of properties associated with the identity */
    properties?: Letta.IdentityProperty[];
}
