/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents the initial tool rule configuration.
 */
export interface InitToolRule {
    /** The name of the tool. Must exist in the database for the user's organization. */
    toolName: string;
    type: "run_first";
    /** Optional template string (ignored). Rendering uses fast built-in formatting for performance. */
    promptTemplate?: string;
}
