/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the job.
 */
export type JobStatus = "not_started" | "created" | "running" | "completed" | "failed" | "pending" | "cancelled";
export const JobStatus = {
    NotStarted: "not_started",
    Created: "created",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
    Pending: "pending",
    Cancelled: "cancelled",
} as const;
