/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LettaResponseToolReturnMessageStatus = "success" | "error";
export const LettaResponseToolReturnMessageStatus = {
    Success: "success",
    Error: "error",
} as const;
