/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index";

export interface LettaSchemasOpenaiOpenaiToolCall {
    /** The unique identifier of the tool call. */
    id: string;
    type?: string;
    /** The function call. */
    function: Letta.Function;
}
