/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index";

/**
 * Represents the in-context memory of the agent. This includes both the `Block` objects (labelled by sections), as well as tools to edit the blocks.
 *
 * Attributes:
 *     memory (Dict[str, Block]): Mapping from memory block section to memory block.
 */
export interface Memory {
    /** Mapping from memory block section to memory block. */
    memory?: Record<string, Letta.Block>;
    /** Jinja2 template for compiling memory blocks into a prompt string */
    prompt_template?: string;
}
