/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

/**
 * Complete metadata response for organization sources
 */
export interface OrganizationSourcesStats {
    /** Total number of sources */
    total_sources?: number;
    /** Total number of files across all sources */
    total_files?: number;
    /** Total size of all files in bytes */
    total_size?: number;
    /** List of source metadata */
    sources?: Letta.SourceStats[];
}
