/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

export interface Provider {
    /** The id of the provider, lazily created by the database manager. */
    id?: string;
    /** The name of the provider */
    name: string;
    /** The type of the provider */
    provider_type: Letta.ProviderType;
    /** The category of the provider (base or byok) */
    provider_category: Letta.ProviderCategory;
    /** API key or secret key used for requests to the provider. */
    api_key?: string;
    /** Base URL for the provider. */
    base_url?: string;
    /** Access key used for requests to the provider. */
    access_key?: string;
    /** Region used for requests to the provider. */
    region?: string;
    /** The last update timestamp of the provider. */
    updated_at?: string;
}
