/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Letta's internal representation of a provider trace.
 *
 * Attributes:
 *     id (str): The unique identifier of the provider trace.
 *     request_json (Dict[str, Any]): JSON content of the provider request.
 *     response_json (Dict[str, Any]): JSON content of the provider response.
 *     step_id (str): ID of the step that this trace is associated with.
 *     organization_id (str): The unique identifier of the organization.
 *     created_at (datetime): The timestamp when the object was created.
 */
export interface ProviderTrace {
    /** The id of the user that made this object. */
    created_by_id?: string;
    /** The id of the user that made this object. */
    last_updated_by_id?: string;
    /** The timestamp when the object was created. */
    created_at?: string;
    /** The timestamp when the object was last updated. */
    updated_at?: string;
    /** The human-friendly ID of the Provider_trace */
    id?: string;
    /** JSON content of the provider request */
    request_json: Record<string, unknown>;
    /** JSON content of the provider response */
    response_json: Record<string, unknown>;
    /** ID of the step that this trace is associated with */
    step_id?: string;
}
