/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

export interface ProviderCheck {
    /** The type of the provider. */
    provider_type: Letta.ProviderType;
    /** API key or secret key used for requests to the provider. */
    api_key: string;
    /** Access key used for requests to the provider. */
    access_key?: string;
    /** Region used for requests to the provider. */
    region?: string;
}
