/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

/**
 * Pydantic model for updating SandboxConfig fields.
 */
export interface SandboxConfigUpdate {
    /** The JSON configuration data for the sandbox. */
    config?: SandboxConfigUpdate.Config;
}

export namespace SandboxConfigUpdate {
    /**
     * The JSON configuration data for the sandbox.
     */
    export type Config = Letta.LocalSandboxConfig | Letta.E2BSandboxConfig | Letta.ModalSandboxConfig;
}
