/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StepFeedback = "positive" | "negative";
export const StepFeedback = {
    Positive: "positive",
    Negative: "negative",
} as const;
