/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A message generated by the system. Never streamed back on a response, only used for cursor pagination.
 *
 * Args:
 *     id (str): The ID of the message
 *     date (datetime): The date the message was created in ISO format
 *     name (Optional[str]): The name of the sender of the message
 *     content (str): The message content sent by the system
 */
export interface SystemMessage {
    id: string;
    date: string;
    name?: string;
    message_type: "system_message";
    otid?: string;
    sender_id?: string;
    step_id?: string;
    is_err?: boolean;
    /** The message content sent by the system */
    content: string;
}
