/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index";

export interface ToolInput {
    type?: "function";
    function: Letta.FunctionSchema;
}
