/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../index.js";

/**
 * A message sent by the user. Never streamed back on a response, only used for cursor pagination.
 *
 * Args:
 *     id (str): The ID of the message
 *     date (datetime): The date the message was created in ISO format
 *     name (Optional[str]): The name of the sender of the message
 *     content (Union[str, List[LettaUserMessageContentUnion]]): The message content sent by the user (can be a string or an array of multi-modal content parts)
 */
export interface UserMessage {
    id: string;
    date: string;
    name?: string;
    message_type: "user_message";
    otid?: string;
    sender_id?: string;
    step_id?: string;
    is_err?: boolean;
    /** The message content sent by the user (can be a string or an array of multi-modal content parts) */
    content: UserMessage.Content;
}

export namespace UserMessage {
    /**
     * The message content sent by the user (can be a string or an array of multi-modal content parts)
     */
    export type Content = Letta.LettaUserMessageContentUnion[] | string;
}
