/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supported vector database providers for archival memory
 */
export type VectorDbProvider = "native" | "tpuf" | "pinecone";
export const VectorDbProvider = {
    Native: "native",
    Tpuf: "tpuf",
    Pinecone: "pinecone",
} as const;
