/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WebSearchOptionsSearchContextSize = "low" | "medium" | "high";
export const WebSearchOptionsSearchContextSize = {
    Low: "low",
    Medium: "medium",
    High: "high",
} as const;
