/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Letta from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { FeedbackType } from "../../../../../../types/FeedbackType";

export const AddFeedbackRequest: core.serialization.Schema<
    serializers.steps.AddFeedbackRequest.Raw,
    Letta.steps.AddFeedbackRequest
> = core.serialization.object({
    feedback: FeedbackType.optional(),
    tags: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AddFeedbackRequest {
    export interface Raw {
        feedback?: FeedbackType.Raw | null;
        tags?: string[] | null;
    }
}
