/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Letta from "../../../../../api/index";
import * as core from "../../../../../core";

export const TemplatesForkTemplateRequest: core.serialization.Schema<
    serializers.TemplatesForkTemplateRequest.Raw,
    Letta.TemplatesForkTemplateRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
});

export declare namespace TemplatesForkTemplateRequest {
    export interface Raw {
        name?: string | null;
    }
}
