/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Letta from "../../../../../api/index";
import * as core from "../../../../../core";

export const TemplatesMigrateDeploymentRequest: core.serialization.Schema<
    serializers.TemplatesMigrateDeploymentRequest.Raw,
    Letta.TemplatesMigrateDeploymentRequest
> = core.serialization.object({
    version: core.serialization.string(),
    preserveToolVariables: core.serialization.property(
        "preserve_tool_variables",
        core.serialization.boolean().optional(),
    ),
    preserveCoreMemories: core.serialization.property(
        "preserve_core_memories",
        core.serialization.boolean().optional(),
    ),
    memoryVariables: core.serialization.property(
        "memory_variables",
        core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    ),
});

export declare namespace TemplatesMigrateDeploymentRequest {
    export interface Raw {
        version: string;
        preserve_tool_variables?: boolean | null;
        preserve_core_memories?: boolean | null;
        memory_variables?: Record<string, string> | null;
    }
}
