/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface TemplatesCreateVersionRequest {
    returnAgentState?: Letta.agents.TemplatesCreateVersionRequestReturnAgentState;
    migrate_deployed_agents?: boolean;
    message?: string;
}
