/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../index";

export type TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken =
    | string
    | string
    | undefined
    | (Letta.TemplatesCreateAgentsResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem | undefined)[]
    | unknown;
