/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../index";

export interface TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemFour {
    toolName: string;
    type?: Letta.TemplatesCreateAgentsResponseAgentsItemToolRulesItemItemFourType;
}
