/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemChildrenType =
    | "constrain_child_tools"
    | unknown;
