/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../index";

export type TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplate =
    | string
    | string
    | undefined
    | (Letta.TemplatesCreateAgentsFromTemplateResponseAgentsItemToolRulesItemItemOnePromptTemplateItem | undefined)[]
    | unknown;
