/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplatesGetTemplateSnapshotResponseAgentsItemAgentType =
    | "memgpt_agent"
    | "memgpt_v2_agent"
    | "react_agent"
    | "workflow_agent"
    | "split_thread_agent"
    | "sleeptime_agent"
    | "voice_convo_agent"
    | "voice_sleeptime_agent";
export const TemplatesGetTemplateSnapshotResponseAgentsItemAgentType = {
    MemgptAgent: "memgpt_agent",
    MemgptV2Agent: "memgpt_v2_agent",
    ReactAgent: "react_agent",
    WorkflowAgent: "workflow_agent",
    SplitThreadAgent: "split_thread_agent",
    SleeptimeAgent: "sleeptime_agent",
    VoiceConvoAgent: "voice_convo_agent",
    VoiceSleeptimeAgent: "voice_sleeptime_agent",
} as const;
