/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType =
    | "openai"
    | "anthropic"
    | "google_ai"
    | "google_vertex"
    | "azure"
    | "groq"
    | "ollama"
    | "webui"
    | "webui-legacy"
    | "lmstudio"
    | "lmstudio-legacy"
    | "lmstudio-chatcompletions"
    | "llamacpp"
    | "koboldcpp"
    | "vllm"
    | "hugging-face"
    | "mistral"
    | "together"
    | "bedrock"
    | "deepseek"
    | "xai";
export const TemplatesCreateAgentsFromTemplateResponseAgentsItemLlmConfigModelEndpointType = {
    Openai: "openai",
    Anthropic: "anthropic",
    GoogleAi: "google_ai",
    GoogleVertex: "google_vertex",
    Azure: "azure",
    Groq: "groq",
    Ollama: "ollama",
    Webui: "webui",
    WebuiLegacy: "webui-legacy",
    Lmstudio: "lmstudio",
    LmstudioLegacy: "lmstudio-legacy",
    LmstudioChatcompletions: "lmstudio-chatcompletions",
    Llamacpp: "llamacpp",
    Koboldcpp: "koboldcpp",
    Vllm: "vllm",
    HuggingFace: "hugging-face",
    Mistral: "mistral",
    Together: "together",
    Bedrock: "bedrock",
    Deepseek: "deepseek",
    Xai: "xai",
} as const;
