/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const ApprovalReturn: core.serialization.ObjectSchema<serializers.ApprovalReturn.Raw, Letta.ApprovalReturn> =
    core.serialization.object({
        type: core.serialization.stringLiteral("approval"),
        toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
        approve: core.serialization.boolean(),
        reason: core.serialization.string().optional(),
    });

export declare namespace ApprovalReturn {
    export interface Raw {
        type: "approval";
        tool_call_id: string;
        approve: boolean;
        reason?: string | null;
    }
}
