/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const AssistantFile: core.serialization.ObjectSchema<serializers.AssistantFile.Raw, Letta.AssistantFile> =
    core.serialization.object({
        id: core.serialization.string(),
        object: core.serialization.string().optional(),
        createdAt: core.serialization.property("created_at", core.serialization.number()),
        assistantId: core.serialization.property("assistant_id", core.serialization.string()),
    });

export declare namespace AssistantFile {
    interface Raw {
        id: string;
        object?: string | null;
        created_at: number;
        assistant_id: string;
    }
}
