/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const AssistantMessage: core.serialization.ObjectSchema<
    serializers.AssistantMessage.Raw,
    Letta.AssistantMessage
> = core.serialization.object({
    id: core.serialization.string(),
    date: core.serialization.date(),
    messageType: core.serialization.property("message_type", core.serialization.stringLiteral("assistant_message")),
    assistantMessage: core.serialization.property("assistant_message", core.serialization.string()),
});

export declare namespace AssistantMessage {
    export interface Raw {
        id: string;
        date: string;
        message_type: "assistant_message";
        assistant_message: string;
    }
}
