/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const ChatCompletionContentPartRefusalParam: core.serialization.ObjectSchema<
    serializers.ChatCompletionContentPartRefusalParam.Raw,
    Letta.ChatCompletionContentPartRefusalParam
> = core.serialization.object({
    refusal: core.serialization.string(),
    type: core.serialization.stringLiteral("refusal"),
});

export declare namespace ChatCompletionContentPartRefusalParam {
    export interface Raw {
        refusal: string;
        type: "refusal";
    }
}
