/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";
import { ChatCompletionMessageFunctionToolCallOutput } from "./ChatCompletionMessageFunctionToolCallOutput";
import { ChatCompletionMessageCustomToolCall } from "./ChatCompletionMessageCustomToolCall";

export const ChatCompletionMessageToolCallsItem: core.serialization.Schema<
    serializers.ChatCompletionMessageToolCallsItem.Raw,
    Letta.ChatCompletionMessageToolCallsItem
> = core.serialization.undiscriminatedUnion([
    ChatCompletionMessageFunctionToolCallOutput,
    ChatCompletionMessageCustomToolCall,
]);

export declare namespace ChatCompletionMessageToolCallsItem {
    export type Raw = ChatCompletionMessageFunctionToolCallOutput.Raw | ChatCompletionMessageCustomToolCall.Raw;
}
