/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const CompletionCreateParamsStreamingServiceTier: core.serialization.Schema<
    serializers.CompletionCreateParamsStreamingServiceTier.Raw,
    Letta.CompletionCreateParamsStreamingServiceTier
> = core.serialization.enum_(["auto", "default", "flex"]);

export declare namespace CompletionCreateParamsStreamingServiceTier {
    export type Raw = "auto" | "default" | "flex";
}
