/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const CustomInput: core.serialization.ObjectSchema<serializers.CustomInput.Raw, Letta.CustomInput> =
    core.serialization.object({
        input: core.serialization.string(),
        name: core.serialization.string(),
    });

export declare namespace CustomInput {
    export interface Raw {
        input: string;
        name: string;
    }
}
