/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const Function: core.serialization.ObjectSchema<serializers.Function.Raw, Letta.Function> = core.serialization
    .object({
        arguments: core.serialization.string(),
        name: core.serialization.string(),
    })
    .passthrough();

export declare namespace Function {
    export interface Raw {
        arguments: string;
        name: string;
        [key: string]: any;
    }
}
