/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const ImportedAgentsResponse: core.serialization.ObjectSchema<
    serializers.ImportedAgentsResponse.Raw,
    Letta.ImportedAgentsResponse
> = core.serialization.object({
    agentIds: core.serialization.property("agent_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace ImportedAgentsResponse {
    export interface Raw {
        agent_ids: string[];
    }
}
