/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const InternalTemplateBlockCreate: core.serialization.ObjectSchema<
    serializers.InternalTemplateBlockCreate.Raw,
    Letta.InternalTemplateBlockCreate
> = core.serialization.object({
    value: core.serialization.string(),
    limit: core.serialization.number().optional(),
    projectId: core.serialization.property("project_id", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    isTemplate: core.serialization.property("is_template", core.serialization.boolean().optional()),
    templateId: core.serialization.property("template_id", core.serialization.string()),
    baseTemplateId: core.serialization.property("base_template_id", core.serialization.string()),
    deploymentId: core.serialization.property("deployment_id", core.serialization.string()),
    entityId: core.serialization.property("entity_id", core.serialization.string()),
    preserveOnMigration: core.serialization.property("preserve_on_migration", core.serialization.boolean().optional()),
    label: core.serialization.string(),
    readOnly: core.serialization.property("read_only", core.serialization.boolean().optional()),
    description: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace InternalTemplateBlockCreate {
    export interface Raw {
        value: string;
        limit?: number | null;
        project_id?: string | null;
        name?: string | null;
        is_template?: boolean | null;
        template_id: string;
        base_template_id: string;
        deployment_id: string;
        entity_id: string;
        preserve_on_migration?: boolean | null;
        label: string;
        read_only?: boolean | null;
        description?: string | null;
        metadata?: Record<string, unknown> | null;
    }
}
