/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";
import { FunctionCallOutput } from "./FunctionCallOutput";

export const LettaSchemasOpenaiChatCompletionResponseToolCall: core.serialization.ObjectSchema<
    serializers.LettaSchemasOpenaiChatCompletionResponseToolCall.Raw,
    Letta.LettaSchemasOpenaiChatCompletionResponseToolCall
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("function").optional(),
    function: FunctionCallOutput,
});

export declare namespace LettaSchemasOpenaiChatCompletionResponseToolCall {
    interface Raw {
        id: string;
        type?: "function" | null;
        function: FunctionCallOutput.Raw;
    }
}
