/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";
import { Message } from "./Message";

export const LettaBatchMessages: core.serialization.ObjectSchema<
    serializers.LettaBatchMessages.Raw,
    Letta.LettaBatchMessages
> = core.serialization.object({
    messages: core.serialization.list(Message),
});

export declare namespace LettaBatchMessages {
    export interface Raw {
        messages: Message.Raw[];
    }
}
