/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const LettaSchemasMessageToolReturnStatus: core.serialization.Schema<
    serializers.LettaSchemasMessageToolReturnStatus.Raw,
    Letta.LettaSchemasMessageToolReturnStatus
> = core.serialization.enum_(["success", "error"]);

export declare namespace LettaSchemasMessageToolReturnStatus {
    export type Raw = "success" | "error";
}
