/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const MaxCountPerStepToolRuleSchema: core.serialization.ObjectSchema<
    serializers.MaxCountPerStepToolRuleSchema.Raw,
    Letta.MaxCountPerStepToolRuleSchema
> = core.serialization.object({
    toolName: core.serialization.property("tool_name", core.serialization.string()),
    type: core.serialization.string(),
    maxCountLimit: core.serialization.property("max_count_limit", core.serialization.number()),
});

export declare namespace MaxCountPerStepToolRuleSchema {
    export interface Raw {
        tool_name: string;
        type: string;
        max_count_limit: number;
    }
}
