/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";
import { Message } from "./Message";

export const MessageSearchResult: core.serialization.ObjectSchema<
    serializers.MessageSearchResult.Raw,
    Letta.MessageSearchResult
> = core.serialization.object({
    embeddedText: core.serialization.property("embedded_text", core.serialization.string()),
    message: Message,
    ftsRank: core.serialization.property("fts_rank", core.serialization.number().optional()),
    vectorRank: core.serialization.property("vector_rank", core.serialization.number().optional()),
    rrfScore: core.serialization.property("rrf_score", core.serialization.number()),
});

export declare namespace MessageSearchResult {
    export interface Raw {
        embedded_text: string;
        message: Message.Raw;
        fts_rank?: number | null;
        vector_rank?: number | null;
        rrf_score: number;
    }
}
