/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction: core.serialization.ObjectSchema<
    serializers.OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction.Raw,
    Letta.OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace OpenaiTypesChatChatCompletionNamedToolChoiceParamFunction {
    export interface Raw {
        name: string;
    }
}
