/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const RunMetrics: core.serialization.ObjectSchema<serializers.RunMetrics.Raw, Letta.RunMetrics> =
    core.serialization.object({
        id: core.serialization.string(),
        agentId: core.serialization.property("agent_id", core.serialization.string().optional()),
        projectId: core.serialization.property("project_id", core.serialization.string().optional()),
        runStartNs: core.serialization.property("run_start_ns", core.serialization.number().optional()),
        runNs: core.serialization.property("run_ns", core.serialization.number().optional()),
        numSteps: core.serialization.property("num_steps", core.serialization.number().optional()),
        templateId: core.serialization.property("template_id", core.serialization.string().optional()),
        baseTemplateId: core.serialization.property("base_template_id", core.serialization.string().optional()),
    });

export declare namespace RunMetrics {
    export interface Raw {
        id: string;
        agent_id?: string | null;
        project_id?: string | null;
        run_start_ns?: number | null;
        run_ns?: number | null;
        num_steps?: number | null;
        template_id?: string | null;
        base_template_id?: string | null;
    }
}
