/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const ToolReturnMessageStatus: core.serialization.Schema<
    serializers.ToolReturnMessageStatus.Raw,
    Letta.ToolReturnMessageStatus
> = core.serialization.enum_(["success", "error"]);

export declare namespace ToolReturnMessageStatus {
    type Raw = "success" | "error";
}
