/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const UrlImage: core.serialization.ObjectSchema<serializers.UrlImage.Raw, Letta.UrlImage> =
    core.serialization.object({
        type: core.serialization.stringLiteral("url"),
        url: core.serialization.string(),
    });

export declare namespace UrlImage {
    export interface Raw {
        type: "url";
        url: string;
    }
}
