/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";
import { UserMessageInputContent } from "./UserMessageInputContent";

export const UserMessageInput: core.serialization.ObjectSchema<
    serializers.UserMessageInput.Raw,
    Letta.UserMessageInput
> = core.serialization.object({
    content: UserMessageInputContent,
    role: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace UserMessageInput {
    interface Raw {
        content: UserMessageInputContent.Raw;
        role?: string | null;
        name?: string | null;
    }
}
