/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Letta from "../../api/index";
import * as core from "../../core";

export const UserMessageOutput: core.serialization.ObjectSchema<
    serializers.UserMessageOutput.Raw,
    Letta.UserMessageOutput
> = core.serialization.object({
    id: core.serialization.string(),
    date: core.serialization.date(),
    message: core.serialization.string(),
});

export declare namespace UserMessageOutput {
    export interface Raw {
        id: string;
        date: string;
        message: string;
    }
}
