/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../index";

export type AgentsSearchResponseAgentsItemIdentifierKey =
    | string
    | string
    | undefined
    | (Letta.AgentsSearchResponseAgentsItemIdentifierKeyItem | undefined)[]
    | unknown;
