/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentsSearchResponseAgentsItemMultiAgentGroupAgentIdsManagerType =
    | "round_robin"
    | "supervisor"
    | "dynamic"
    | "swarm";
export const AgentsSearchResponseAgentsItemMultiAgentGroupAgentIdsManagerType = {
    RoundRobin: "round_robin",
    Supervisor: "supervisor",
    Dynamic: "dynamic",
    Swarm: "swarm",
} as const;
