/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../index";

export type AgentsSearchResponseAgentsItemMultiAgentGroupAgentIdsTerminationToken =
    | string
    | string
    | undefined
    | (Letta.AgentsSearchResponseAgentsItemMultiAgentGroupAgentIdsTerminationTokenItem | undefined)[]
    | unknown;
