/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentsSearchDeployedAgentsRequestSearchItemDirectionValue = "created_at" | "updated_at";
export const AgentsSearchDeployedAgentsRequestSearchItemDirectionValue = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
} as const;
