/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { LettaClient } from "../../../src/Client";

describe("MemoryVariables", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new LettaClient({ token: "test", project: "test", environment: server.baseUrl });

        const rawResponseBody = { variables: { key: "value" } };
        server
            .mockEndpoint()
            .get("/v1/agents/agent_id/core-memory/variables")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.memoryVariables.list("agent_id");
        expect(response).toEqual({
            variables: {
                key: "value",
            },
        });
    });
});
