/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { LettaClient } from "../../src/Client";

describe("Templates", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new LettaClient({ token: "test", project: "test", environment: server.baseUrl });

        const rawResponseBody = { templates: [{ name: "name", id: "id" }], hasNextPage: true };
        server.mockEndpoint().get("/v1/templates").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.templates.list();
        expect(response).toEqual({
            templates: [
                {
                    name: "name",
                    id: "id",
                },
            ],
            hasNextPage: true,
        });
    });
});
