/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Letta from "../../../../../index";

export type AgentsCreateResponseGroupTurnsCounter =
    | number
    | string
    | undefined
    | (Letta.templates.AgentsCreateResponseGroupTurnsCounterItem | undefined)[]
    | unknown;
