name: tests

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Test
        env:
            LETTA_API_KEY: ${{ secrets.LETTA_API_KEY }}
        run: yarn && yarn test tests/custom.test.ts