/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Letta from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FilesListRequestOrder: core.serialization.Schema<
    serializers.folders.FilesListRequestOrder.Raw,
    Letta.folders.FilesListRequestOrder
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace FilesListRequestOrder {
    export type Raw = "asc" | "desc";
}
